// LEFT SIDE
export const LEFT_SIDE =
{
    GET_CONTACTS: 'LEFT_SITE_GET_CONTACTS',
    DEL_CONTACT: 'LEFT_SDE_DELETE_CONTACTS'
}
// WINDOW CHAT
export const WINDOW_CHAT =
{
    GET_CHAT_HISTORY: 'GET_CHAT_HISTORY',
    SEND_MESSAGE: 'SEND_A_MESSAGE',
    GET_CONTACT_INFO: 'GET_CONTACT_INFO'
}
// Contact
export const CONTACTS = {
    GET_CONTACTS: 'GET_CONTACTS',
    DEL_CONTACT: 'DELETE_CONTACTS'
};
// Login
export const AUTHORIZE = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
}